package com.obsIA.domain

import com.obsIA.domain.model.ClinicalResponse
import com.obsIA.domain.model.UrgencyLevel

/**
 * QueryOrchestrator
 *
 * Coordinates the complete clinical-response flow:
 * 1. Detects whether the query is emergency or routine
 * 2. If emergency, searches for a matching emergency clinical rule
 * 3. If routine, searches for a matching routine clinical rule
 * 4. If no rule is found, delegates the response generation to the LLM engine
 *
 * This class acts as the main application-level coordinator for clinical query processing.
 */
class QueryOrchestrator(
    private val emergencyDetector: EmergencyDetector,
    private val emergencyRules: EmergencyClinicalRules,
    private val routineRules: RoutineClinicalRules,
    private val llmEngine: LlmEngine
) {

    /**
     * Processes a user clinical query and returns a structured response.
     *
     * @param query User input in natural language
     * @return A ClinicalResponse representing the system output
     */
    fun process(query: String): ClinicalResponse {

        // Step 1: Determine urgency level
        val urgency = emergencyDetector.analizar(query)

        // Step 2: If emergency, try to resolve using emergency clinical rules
        if (urgency == UrgencyLevel.EMERGENCY) {
            val emergencyMatch = emergencyRules.lookup(query)

            if (emergencyMatch != null) {
                return ClinicalResponse.Emergency(
                    title = emergencyMatch.title,
                    why = emergencyMatch.why,
                    immediateSteps = emergencyMatch.immediate_steps,
                    escalatesWhen = emergencyMatch.escalates_when,
                    triggeredRuleId = emergencyMatch.id
                )
            }

            // Fallback: emergency detected but no specific rule matched
            return ClinicalResponse.Emergency(
                title = "Emergency obstetric condition detected",
                why = "The query contains indicators associated with an obstetric emergency.",
                immediateSteps = listOf("Call emergency services immediately."),
                escalatesWhen = "At any time without urgent medical attention.",
                triggeredRuleId = "GENERIC"
            )
        }

        // Step 3: Try to resolve with routine clinical rules
        val routineMatch = routineRules.lookup(query)
        if (routineMatch != null) {
            return ClinicalResponse.RuleMatch(
                context = routineMatch.context,
                response = routineMatch.response,
                whenToConsult = routineMatch.when_to_consult,
                ruleId = routineMatch.id
            )
        }

        // Step 4: Fallback to local LLM generation
        // TODO: Replace stub implementation with JNI-based LLM engine integration
        return ClinicalResponse.LlmGenerated(
            responseText = llmEngine.infer(query),
            urgencyLevel = urgency
        )
    }
}

/**
 * Abstraction for the local LLM engine.
 *
 * This allows the orchestrator to remain independent from the concrete
 * implementation details of JNI, llama.cpp, or any future inference engine.
 */
interface LlmEngine {

    /**
     * Generates a response for a user query.
     *
     * @param query User input text
     * @return Generated response text
     */
    fun infer(query: String): String
}

/**
 * Temporary stub implementation of the LLM engine.
 *
 * Used during development before JNI integration is completed.
 */
class LlmEngineStub : LlmEngine {

    /**
     * Returns a placeholder generated response.
     *
     * @param query User input text
     * @return Stubbed response including mandatory disclaimer
     */
    override fun infer(query: String): String {
        return "Response generated by local LLM (stub mode). ${ClinicalResponse.DISCLAIMER}"
    }
}
